### ISSUE TITLE
Consistency level ONE is not suppoprted for this operation

### ISSUE THREAD

**Issue by Xaptor** [AERC18/cdrs-aws-cassandra#1]
Hi,

trying the example from this repository connecting -> create keyspace -> create table works fine but inserting throws the following  error.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Server(CDRSError { error_code: 8704, message: CString { string: "Consistency level ONE is not supported for this operation. Supported consistency levels are: LOCAL_QUORUM" }, additional_info: Invalid(SimpleError) })', src/main.rs:86:47

Can anybody confirm that the example is still working? If yes where do I have to change the consistency level with query_with_values() ?

**Comment by AERC18** [comment]
Hi, I have look into it and have fixed the example. Please sync your code with the `master` branch and this should be solved.
